Repository crismantovani/projeto-traveller, pull requests merged in 2022-04, with the labels that each got.

#6 feat: :sparkles: CORRIGE constraste dos botões
  index.html
  style.css
Labels: enhancement

#9 Bugfix/radio buttons
  index.html
  style.css
Labels: bug

#14 feat: :sparkles: CRIA descrição para imagens
  index.html
Labels: enhancement

#15 fix: :bug: CORRIGE bug de ID do datalist
  index.html
  style.css
Labels: bug

#19 Feature/estrutura html sections
  index.html
  style.css
Labels: bug, enhancement

#21 feat: :sparkles: CRIA acessibilidade em todo o site
  index.html
  style.css
Labels: bug, enhancement

#23 feat: :sparkles: VLibras & Responsividadade
  index.html
  style.css
Labels: bug, enhancement
